//! Type `1_006_001`: `pg_stat_bgwriter` + `pg_stat_checkpointer`, a
//! single-row snapshot (README.md, "Example: type `1_006_001`").
//!
//! One codec spans every `PostgreSQL` version. PG17 reorganized these stats:
//! the checkpoint counters moved from `pg_stat_bgwriter` to
//! `pg_stat_checkpointer` and several were renamed (`buffers_checkpoint` →
//! `buffers_written`, now counting restartpoints too); PG17 also added the
//! restartpoint counters and dropped `buffers_backend` /
//! `buffers_backend_fsync`. Each field keeps one stable name and documents its
//! per-version source; a column the running server lacks is `None`, in either
//! direction. Which case applies is read from `instance_metadata`
//! (`pg_version_num`), not encoded as a new `type_id`.
//!
//! Statistics reset is per-view: `pg_stat_reset_shared('bgwriter')` or
//! `('checkpointer')` — or a postmaster restart — zeroes the counters and bumps
//! the view's `stats_reset`. Each row carries its own `*_stats_reset` so the
//! diff code can see a reset that happens in the middle of a segment;
//! `reset_metadata` is one row per segment and would miss it. A reset changing
//! between two rows means the counters above it restarted, so a rate across
//! them is invalid. Which reset applies is version-dependent: checkpoint and
//! restartpoint counters use `checkpointer_stats_reset` on PG17+ and
//! `bgwriter_stats_reset` before PG17.
//!
//! The whole codec — contract, encode, decode — is generated by
//! `#[derive(Section)]` from the struct below. The struct is the only
//! per-type code: the field types give the on-disk types and nullability,
//! and the `#[column(..)]` class gives the diff/chart role.

use crate::{Section, Ts};

/// One row of type `1_006_001`. Fields absent in `PostgreSQL` 17 are `None`.
#[derive(Debug, Clone, Copy, PartialEq, Section)]
#[section(
    id = 1_006_001,
    name = "pg_stat_bgwriter + pg_stat_checkpointer",
    semantics = snapshot_full,
    sort_key("ts")
)]
pub struct BgwriterCheckpointer {
    /// Collection timestamp, unix microseconds.
    #[column(t)]
    pub ts: Ts,
    /// Scheduled checkpoints. `pg_stat_bgwriter.checkpoints_timed` before PG17,
    /// `pg_stat_checkpointer.num_timed` on PG17+. The semantics differ: PG16
    /// counts performed scheduled checkpoints; PG17+ counts both completed and
    /// skipped ones — the checkpointer skips a scheduled checkpoint when no WAL
    /// was written since the last — so on a quiet server the count includes those
    /// skips and is not the rate of real checkpoints, and a delta spanning the
    /// upgrade is not comparable. Same reset split as `checkpoint_write_time`.
    #[column(c)]
    pub checkpoints_timed: i64,
    /// Requested checkpoints. `checkpoints_req` before PG17,
    /// `pg_stat_checkpointer.num_requested` on PG17+. Same reset split as
    /// `checkpoint_write_time`.
    #[column(c)]
    pub checkpoints_req: i64,
    /// Time writing checkpoints, ms. `pg_stat_bgwriter.checkpoint_write_time`
    /// before PG17; `pg_stat_checkpointer.write_time` on PG17+, which also covers
    /// restartpoints — so on a standby, where restartpoints dominate, this is
    /// mostly restartpoint write time despite the `checkpoint_` name. Rate
    /// validity is version-dependent: a delta is valid only within one
    /// `bgwriter_stats_reset` before PG17, or one `checkpointer_stats_reset` on
    /// PG17+ — dividing by the wrong reset yields a spurious negative or zero
    /// after an independent checkpointer reset.
    #[column(c)]
    pub checkpoint_write_time: f64,
    /// Time syncing checkpoints, ms. `pg_stat_bgwriter.checkpoint_sync_time`
    /// before PG17; `pg_stat_checkpointer.sync_time` on PG17+ (which also covers
    /// restartpoints). Same source-and-reset split as `checkpoint_write_time`.
    #[column(c)]
    pub checkpoint_sync_time: f64,
    /// Buffers written during checkpoints. `pg_stat_bgwriter.buffers_checkpoint`
    /// before PG17; `pg_stat_checkpointer.buffers_written` on PG17+. PG17 made the
    /// column description explicitly include restartpoint buffer writes on a
    /// standby; the pre-PG17 docs only said "during checkpoints". The write path
    /// is the same, but treat a delta spanning the upgrade on a standby as suspect
    /// rather than assuming exact equivalence. Same reset split as
    /// `checkpoint_write_time`.
    #[column(c)]
    pub buffers_checkpoint: i64,
    /// Scheduled restartpoints, the checkpoint path on a hot standby.
    /// `pg_stat_checkpointer.restartpoints_timed`; `None` before PG17. PG17 counts
    /// these "due to timeout or after a failed attempt to perform it", so a
    /// failed-and-retried restartpoint bumps this without a matching
    /// `restartpoints_done`.
    #[column(c)]
    pub restartpoints_timed: Option<i64>,
    /// Requested restartpoints. `pg_stat_checkpointer.restartpoints_req`; `None`
    /// before PG17.
    #[column(c)]
    pub restartpoints_req: Option<i64>,
    /// Completed restartpoints. `pg_stat_checkpointer.restartpoints_done`; `None`
    /// before PG17. On a standby this is the recovery-checkpoint rate; it helps
    /// separate slow WAL replay from lack of incoming WAL.
    #[column(c)]
    pub restartpoints_done: Option<i64>,
    /// Buffers written by the background writer
    /// (`pg_stat_bgwriter.buffers_clean`, both versions).
    #[column(c)]
    pub buffers_clean: i64,
    /// Times the background writer stopped a cleaning scan early
    /// (`pg_stat_bgwriter.maxwritten_clean`, both versions).
    #[column(c)]
    pub maxwritten_clean: i64,
    /// Buffers written by backends; `None` on PG17+, which removed it from
    /// `pg_stat_bgwriter` (the data moved to `pg_stat_io`).
    #[column(c)]
    pub buffers_backend: Option<i64>,
    /// Backend fsync calls; `None` on PG17+ (removed from `pg_stat_bgwriter`).
    #[column(c)]
    pub buffers_backend_fsync: Option<i64>,
    /// Buffers allocated (`pg_stat_bgwriter.buffers_alloc`, both versions).
    #[column(c)]
    pub buffers_alloc: i64,
    /// `pg_stat_bgwriter.stats_reset`: when this view was last reset, by a
    /// manual `pg_stat_reset_shared('bgwriter')` or a postmaster restart. Use it
    /// for background-writer counter rates on all versions and checkpoint counter
    /// rates before PG17, where those counters were in `pg_stat_bgwriter`.
    #[column(g)]
    pub bgwriter_stats_reset: Ts,
    /// `pg_stat_checkpointer.stats_reset`; `None` before PG17, where the
    /// checkpoint counters lived in `pg_stat_bgwriter` and shared its reset. On
    /// PG17+ use this reset for checkpoint and restartpoint counter rates; those
    /// counters reset independently of the background writer.
    #[column(g)]
    pub checkpointer_stats_reset: Option<Ts>,
}

#[cfg(test)]
mod tests {
    use super::BgwriterCheckpointer;
    use crate::{
        CodecError, MAX_SECTION_BYTES, MAX_SECTION_ROWS, Section, Ts, VerifiedSection, lint,
    };

    fn pg16_row(ts: i64) -> BgwriterCheckpointer {
        BgwriterCheckpointer {
            ts: Ts(ts),
            checkpoints_timed: 10,
            checkpoints_req: 2,
            checkpoint_write_time: 1234.5,
            checkpoint_sync_time: 67.0,
            buffers_checkpoint: 4096,
            restartpoints_timed: None,
            restartpoints_req: None,
            restartpoints_done: None,
            buffers_clean: 512,
            maxwritten_clean: 3,
            buffers_backend: Some(128),
            buffers_backend_fsync: Some(0),
            buffers_alloc: 9000,
            bgwriter_stats_reset: Ts(ts - 100_000),
            checkpointer_stats_reset: None,
        }
    }

    fn pg17_row(ts: i64) -> BgwriterCheckpointer {
        BgwriterCheckpointer {
            buffers_backend: None,
            buffers_backend_fsync: None,
            restartpoints_timed: Some(7),
            restartpoints_req: Some(1),
            restartpoints_done: Some(6),
            checkpointer_stats_reset: Some(Ts(ts - 50_000)),
            ..pg16_row(ts)
        }
    }

    #[test]
    fn contract_passes_the_linter() {
        assert_eq!(lint(&[BgwriterCheckpointer::CONTRACT]), Ok(()));
    }

    #[test]
    fn contract_shape_matches_the_source() {
        let c = BgwriterCheckpointer::CONTRACT;
        assert_eq!(c.type_id.get(), 1_006_001);
        assert_eq!(c.columns.len(), 16);
        assert_eq!(c.sort_key, ["ts"]);
        // `ts` is the sort timestamp. Nullable columns cover PG17-only
        // counters, counters removed from `pg_stat_bgwriter` in PG17, and the
        // checkpointer reset.
        assert_eq!(c.column("ts").map(|col| col.nullable), Some(false));
        assert_eq!(
            c.column("buffers_backend").map(|col| col.nullable),
            Some(true)
        );
        assert_eq!(
            c.column("restartpoints_done").map(|col| col.nullable),
            Some(true)
        );
        assert_eq!(
            c.column("buffers_checkpoint").map(|col| col.nullable),
            Some(false)
        );
        assert_eq!(
            c.column("checkpointer_stats_reset").map(|col| col.nullable),
            Some(true)
        );
    }

    #[test]
    fn roundtrip_preserves_values_and_nulls() {
        // One section may contain rows from both PostgreSQL layouts.
        crate::assert_roundtrips(&[pg16_row(1_000_000), pg17_row(2_000_000)]);
    }

    #[test]
    fn encode_sorts_rows_by_the_sort_key() {
        // Rows given out of `ts` order come back sorted: encode orders by the
        // contract sort key for compression.
        let bytes = BgwriterCheckpointer::encode(&[pg17_row(2_000_000), pg16_row(1_000_000)])
            .expect("encode");
        let decoded =
            BgwriterCheckpointer::decode(VerifiedSection::for_test(bytes.into())).expect("decode");
        assert_eq!(
            decoded.iter().map(|row| row.ts.0).collect::<Vec<_>>(),
            [1_000_000, 2_000_000]
        );
    }

    #[test]
    fn decode_any_reports_stats() {
        let rows = vec![pg16_row(1_000_000), pg17_row(2_000_000)];
        let bytes = BgwriterCheckpointer::encode(&rows).expect("encode");
        let bytes_in = bytes.len();
        let decoded = crate::decode_any(1_006_001, VerifiedSection::for_test(bytes.into()))
            .expect("decode_any");
        assert_eq!(decoded.stats.type_id, 1_006_001);
        assert_eq!(decoded.stats.rows, 2);
        assert_eq!(decoded.stats.bytes_in, bytes_in);
        assert_eq!(decoded.stats.batches, decoded.batches.len());
        assert!(decoded.stats.row_groups >= 1);
    }

    #[test]
    fn empty_section_roundtrips() {
        let bytes = BgwriterCheckpointer::encode(&[]).expect("encode empty");
        assert_eq!(
            BgwriterCheckpointer::decode(VerifiedSection::for_test(bytes.into()))
                .expect("decode empty"),
            Vec::new()
        );
    }

    #[test]
    fn nulls_survive_distinct_from_zero() {
        // NULL must not decode to Some(0).
        let row = pg17_row(5);
        let bytes = BgwriterCheckpointer::encode(&[row]).expect("encode");
        let decoded =
            BgwriterCheckpointer::decode(VerifiedSection::for_test(bytes.into())).expect("decode");
        assert_eq!(decoded[0].buffers_backend, None);
    }

    #[test]
    fn section_is_a_parquet_file() {
        // The body is a self-contained Parquet file: "PAR1" at both ends.
        let bytes = BgwriterCheckpointer::encode(&[pg16_row(1)]).expect("encode");
        assert_eq!(&bytes[..4], b"PAR1");
        assert_eq!(&bytes[bytes.len() - 4..], b"PAR1");
    }

    #[test]
    fn section_does_not_embed_the_arrow_schema() {
        // The contract already defines the schema; arrow-rs would otherwise
        // write a second copy as an "ARROW:schema" key-value blob.
        let bytes = BgwriterCheckpointer::encode(&[pg16_row(1)]).expect("encode");
        let needle = b"ARROW:schema";
        assert!(
            !bytes.windows(needle.len()).any(|w| w == needle),
            "section contains an embedded Arrow schema blob"
        );
    }

    #[test]
    fn encode_is_deterministic() {
        let rows = [pg16_row(1), pg17_row(2)];
        assert_eq!(
            BgwriterCheckpointer::encode(&rows).expect("a"),
            BgwriterCheckpointer::encode(&rows).expect("b")
        );
    }

    #[test]
    fn encode_rejects_too_many_rows() {
        let rows = vec![pg16_row(0); MAX_SECTION_ROWS + 1];
        assert!(matches!(
            BgwriterCheckpointer::encode(&rows),
            Err(CodecError::TooManyRows { .. })
        ));
    }

    #[test]
    fn decode_rejects_an_oversized_section() {
        let bytes = vec![0_u8; MAX_SECTION_BYTES + 1];
        assert!(matches!(
            BgwriterCheckpointer::decode(VerifiedSection::for_test(bytes.into())),
            Err(CodecError::SectionTooLarge { .. })
        ));
    }

    #[test]
    fn typed_decode_rejects_a_schema_that_does_not_match_the_contract() {
        use std::sync::Arc;

        use arrow_array::{ArrayRef, Float64Array, Int64Array, RecordBatch};
        use arrow_schema::{DataType, Field, Schema};
        use parquet::arrow::ArrowWriter;

        // A file with the wrong column set (the pre-PG17 subset, not the full
        // contract) and a nullable `ts`. The typed `Section::decode` validates
        // the schema against the contract before reading rows, exactly as
        // `decode_any` does, so it rejects this with `SchemaMismatch` rather than
        // silently reading the columns it recognizes by name.
        let i64f = |name: &str, nullable: bool| Field::new(name, DataType::Int64, nullable);
        let f64f = |name: &str| Field::new(name, DataType::Float64, false);
        let schema = Arc::new(Schema::new(vec![
            i64f("ts", true),
            i64f("checkpoints_timed", false),
            i64f("checkpoints_req", false),
            f64f("checkpoint_write_time"),
            f64f("checkpoint_sync_time"),
            i64f("buffers_checkpoint", false),
            i64f("buffers_clean", false),
            i64f("maxwritten_clean", false),
            i64f("buffers_backend", true),
            i64f("buffers_backend_fsync", true),
            i64f("buffers_alloc", false),
        ]));
        let columns: Vec<ArrayRef> = vec![
            Arc::new(Int64Array::from(vec![None::<i64>])), // ts = NULL
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Float64Array::from_iter_values([0.0_f64])),
            Arc::new(Float64Array::from_iter_values([0.0_f64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
        ];
        let batch = RecordBatch::try_new(Arc::clone(&schema), columns).expect("batch");

        let mut buf = Vec::new();
        let mut writer = ArrowWriter::try_new(&mut buf, schema, None).expect("writer");
        writer.write(&batch).expect("write");
        writer.close().expect("close");

        assert!(matches!(
            BgwriterCheckpointer::decode(VerifiedSection::for_test(buf.into())),
            Err(CodecError::SchemaMismatch)
        ));
    }
}
