//! Type `1_006_001`: `pg_stat_bgwriter` + `pg_stat_checkpointer`, a
//! single-row snapshot (README.md, "Example: type `1_006_001`").
//!
//! `PostgreSQL` 17 moved some `pg_stat_bgwriter` counters to
//! `pg_stat_checkpointer`. The collector reads both views and writes one row;
//! columns removed from `PostgreSQL` 17 (`buffers_backend`,
//! `buffers_backend_fsync`) are written as `NULL`.
//!
//! The whole codec — contract, encode, decode — is generated by
//! `#[derive(Section)]` from the struct below. The struct is the only
//! per-type code: the field types give the on-disk types and nullability,
//! and the `#[column(..)]` class gives the diff/chart role.

use crate::Section;

/// One row of type `1_006_001`. Fields absent in `PostgreSQL` 17 are `None`.
#[derive(Debug, Clone, Copy, PartialEq, Section)]
#[section(
    id = 1_006_001,
    name = "pg_stat_bgwriter + pg_stat_checkpointer",
    semantics = snapshot_full,
    sort_key("ts")
)]
pub struct BgwriterCheckpointer {
    /// Collection timestamp, unix microseconds.
    #[column(t)]
    pub ts: i64,
    /// Scheduled checkpoints.
    #[column(c)]
    pub checkpoints_timed: i64,
    /// Requested checkpoints.
    #[column(c)]
    pub checkpoints_req: i64,
    /// Time spent writing checkpoints, milliseconds.
    #[column(c)]
    pub checkpoint_write_time: f64,
    /// Time spent syncing checkpoints, milliseconds.
    #[column(c)]
    pub checkpoint_sync_time: f64,
    /// Buffers written during checkpoints.
    #[column(c)]
    pub buffers_checkpoint: i64,
    /// Buffers written by the background writer.
    #[column(c)]
    pub buffers_clean: i64,
    /// Times the background writer stopped a cleaning scan early.
    #[column(c)]
    pub maxwritten_clean: i64,
    /// Buffers written by backends; `None` on PG17+.
    #[column(c)]
    pub buffers_backend: Option<i64>,
    /// Backend fsync calls; `None` on PG17+.
    #[column(c)]
    pub buffers_backend_fsync: Option<i64>,
    /// Buffers allocated.
    #[column(c)]
    pub buffers_alloc: i64,
}

#[cfg(test)]
mod tests {
    use super::BgwriterCheckpointer;
    use crate::{CodecError, MAX_SECTION_BYTES, MAX_SECTION_ROWS, Section, lint};

    fn pg16_row(ts: i64) -> BgwriterCheckpointer {
        BgwriterCheckpointer {
            ts,
            checkpoints_timed: 10,
            checkpoints_req: 2,
            checkpoint_write_time: 1234.5,
            checkpoint_sync_time: 67.0,
            buffers_checkpoint: 4096,
            buffers_clean: 512,
            maxwritten_clean: 3,
            buffers_backend: Some(128),
            buffers_backend_fsync: Some(0),
            buffers_alloc: 9000,
        }
    }

    fn pg17_row(ts: i64) -> BgwriterCheckpointer {
        BgwriterCheckpointer {
            buffers_backend: None,
            buffers_backend_fsync: None,
            ..pg16_row(ts)
        }
    }

    #[test]
    fn contract_passes_the_linter() {
        assert_eq!(lint(&[BgwriterCheckpointer::CONTRACT]), Ok(()));
    }

    #[test]
    fn contract_shape_matches_the_source() {
        let c = BgwriterCheckpointer::CONTRACT;
        assert_eq!(c.type_id.get(), 1_006_001);
        assert_eq!(c.columns.len(), 11);
        assert_eq!(c.sort_key, ["ts"]);
        // ts is the timestamp; the two PG17 casualties are the only nullables.
        assert_eq!(c.column("ts").map(|col| col.nullable), Some(false));
        assert_eq!(
            c.column("buffers_backend").map(|col| col.nullable),
            Some(true)
        );
        assert_eq!(
            c.column("buffers_alloc").map(|col| col.nullable),
            Some(false)
        );
    }

    #[test]
    fn roundtrip_preserves_values_and_nulls() {
        // One section may contain rows from both PostgreSQL layouts.
        let rows = vec![pg16_row(1_000_000), pg17_row(2_000_000)];
        let bytes = BgwriterCheckpointer::encode(&rows).expect("encode");
        let decoded = BgwriterCheckpointer::decode(&bytes).expect("decode");
        assert_eq!(decoded, rows);
    }

    #[test]
    fn empty_section_roundtrips() {
        let bytes = BgwriterCheckpointer::encode(&[]).expect("encode empty");
        assert_eq!(
            BgwriterCheckpointer::decode(&bytes).expect("decode empty"),
            Vec::new()
        );
    }

    #[test]
    fn nulls_survive_distinct_from_zero() {
        // NULL must not decode to Some(0).
        let row = pg17_row(5);
        let bytes = BgwriterCheckpointer::encode(&[row]).expect("encode");
        let decoded = BgwriterCheckpointer::decode(&bytes).expect("decode");
        assert_eq!(decoded[0].buffers_backend, None);
    }

    #[test]
    fn section_is_a_parquet_file() {
        // The body is a self-contained Parquet file: "PAR1" at both ends.
        let bytes = BgwriterCheckpointer::encode(&[pg16_row(1)]).expect("encode");
        assert_eq!(&bytes[..4], b"PAR1");
        assert_eq!(&bytes[bytes.len() - 4..], b"PAR1");
    }

    #[test]
    fn section_does_not_embed_the_arrow_schema() {
        // The contract already defines the schema; arrow-rs would otherwise
        // write a second copy as an "ARROW:schema" key-value blob.
        let bytes = BgwriterCheckpointer::encode(&[pg16_row(1)]).expect("encode");
        let needle = b"ARROW:schema";
        assert!(
            !bytes.windows(needle.len()).any(|w| w == needle),
            "section contains an embedded Arrow schema blob"
        );
    }

    #[test]
    fn encode_is_deterministic() {
        let rows = [pg16_row(1), pg17_row(2)];
        assert_eq!(
            BgwriterCheckpointer::encode(&rows).expect("a"),
            BgwriterCheckpointer::encode(&rows).expect("b")
        );
    }

    #[test]
    fn encode_rejects_too_many_rows() {
        let rows = vec![pg16_row(0); MAX_SECTION_ROWS + 1];
        assert!(matches!(
            BgwriterCheckpointer::encode(&rows),
            Err(CodecError::TooManyRows { .. })
        ));
    }

    #[test]
    fn decode_rejects_an_oversized_section() {
        let bytes = vec![0_u8; MAX_SECTION_BYTES + 1];
        assert!(matches!(
            BgwriterCheckpointer::decode(&bytes),
            Err(CodecError::SectionTooLarge { .. })
        ));
    }

    #[test]
    fn decode_rejects_a_null_in_a_required_column() {
        use std::sync::Arc;

        use arrow_array::{ArrayRef, Float64Array, Int64Array, RecordBatch};
        use arrow_schema::{DataType, Field, Schema};
        use parquet::arrow::ArrowWriter;

        // The columns match the contract, but `ts` is nullable and contains
        // NULL. Required columns must reject NULL rather than read it as zero.
        let i64f = |name: &str, nullable: bool| Field::new(name, DataType::Int64, nullable);
        let f64f = |name: &str| Field::new(name, DataType::Float64, false);
        let schema = Arc::new(Schema::new(vec![
            i64f("ts", true),
            i64f("checkpoints_timed", false),
            i64f("checkpoints_req", false),
            f64f("checkpoint_write_time"),
            f64f("checkpoint_sync_time"),
            i64f("buffers_checkpoint", false),
            i64f("buffers_clean", false),
            i64f("maxwritten_clean", false),
            i64f("buffers_backend", true),
            i64f("buffers_backend_fsync", true),
            i64f("buffers_alloc", false),
        ]));
        let columns: Vec<ArrayRef> = vec![
            Arc::new(Int64Array::from(vec![None::<i64>])), // ts = NULL
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Float64Array::from_iter_values([0.0_f64])),
            Arc::new(Float64Array::from_iter_values([0.0_f64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
            Arc::new(Int64Array::from_iter_values([0_i64])),
        ];
        let batch = RecordBatch::try_new(Arc::clone(&schema), columns).expect("batch");

        let mut buf = Vec::new();
        let mut writer = ArrowWriter::try_new(&mut buf, schema, None).expect("writer");
        writer.write(&batch).expect("write");
        writer.close().expect("close");

        assert!(matches!(
            BgwriterCheckpointer::decode(&buf),
            Err(CodecError::NullInRequiredColumn { name: "ts" })
        ));
    }
}
