//! Section codecs and the shared runtime they are built on.
//!
//! A snapshot section body is a self-contained Parquet file
//! (README.md, "Snapshot Sections"). A type's codec is generated by
//! `#[derive(Section)]` (`kronika-derive`): the derive emits one column
//! builder/reader call per field and delegates the framing, compression,
//! and memory bounds to [`encode_section`] / [`decode_section`] here. This
//! module owns everything type-agnostic — the Arrow schema from the
//! contract, the row/byte/row-group caps, and the column accessors — so a
//! new type cannot drift from the format or forget a bound.

use std::error::Error;
use std::fmt;
use std::sync::Arc;

use arrow_array::{
    Array, ArrayRef, ArrowPrimitiveType, BooleanArray, PrimitiveArray, RecordBatch,
    RecordBatchReader,
};
use arrow_schema::{DataType, Field, Schema, SchemaRef};
use parquet::arrow::ArrowWriter;
use parquet::arrow::arrow_reader::{ParquetRecordBatchReader, ParquetRecordBatchReaderBuilder};
use parquet::arrow::arrow_writer::ArrowWriterOptions;
use parquet::basic::{Compression, ZstdLevel};
use parquet::file::properties::WriterProperties;

use crate::contract::{ColumnType, TypeContract};

pub mod bgwriter_checkpointer;

/// Maximum rows in one snapshot section.
///
/// Enforced memory bound (README.md, "Memory Bounds"): encode rejects larger
/// input slices, and decode rejects larger row counts before allocating arrays.
/// Current single-row sources are much smaller; this limit catches invalid
/// input and writer bugs.
pub const MAX_SECTION_ROWS: usize = 65_536;

/// Maximum accepted section byte length on decode.
///
/// This check runs before Parquet reads file metadata. It bounds how many
/// bytes Parquet can inspect before the registry checks row counts and row
/// groups (README.md, "Memory Bounds"). Current snapshot sections are much
/// smaller.
pub const MAX_SECTION_BYTES: usize = 8 * 1024 * 1024;

/// Maximum Parquet row groups accepted in one snapshot section.
///
/// The current writer emits one row group per section. Decode allows a small
/// margin for future encoders, but rejects sections with many row groups before
/// reading any column data.
pub const MAX_ROW_GROUPS: usize = 16;

/// Why a section failed to encode or decode.
#[derive(Debug)]
pub enum CodecError {
    /// An Arrow operation failed (building the record batch).
    Arrow(arrow_schema::ArrowError),
    /// A Parquet operation failed (writing or reading the file).
    Parquet(parquet::errors::ParquetError),
    /// More rows than [`MAX_SECTION_ROWS`] were given to encode, or a
    /// section claims or holds more on decode.
    TooManyRows {
        /// The row count that exceeded the cap.
        rows: usize,
        /// The enforced cap.
        max: usize,
    },
    /// The section byte length is above [`MAX_SECTION_BYTES`].
    SectionTooLarge {
        /// The byte length that exceeded the cap.
        len: usize,
        /// The enforced cap.
        max: usize,
    },
    /// The section has more than [`MAX_ROW_GROUPS`] row groups.
    TooManyRowGroups {
        /// The row-group count that exceeded the cap.
        groups: usize,
        /// The enforced cap.
        max: usize,
    },
    /// A column required by the contract is absent from the decoded file.
    MissingColumn {
        /// The missing column name.
        name: &'static str,
    },
    /// A decoded column has a different Arrow type than the contract.
    ColumnType {
        /// The column name.
        name: &'static str,
    },
    /// A `NULL` appeared in a column the contract declares non-nullable.
    ///
    /// `NULL` must stay distinct from a real value, so a required column that
    /// decodes as null is a malformed section, not a zero.
    NullInRequiredColumn {
        /// The column name.
        name: &'static str,
    },
    /// No registered type has the requested `type_id`.
    UnknownType {
        /// The unrecognized id.
        type_id: u32,
    },
    /// A decoded section's schema does not match the contract it was decoded
    /// against (column set, order, types, or nullability).
    SchemaMismatch,
}

impl fmt::Display for CodecError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Arrow(err) => write!(f, "arrow: {err}"),
            Self::Parquet(err) => write!(f, "parquet: {err}"),
            Self::TooManyRows { rows, max } => {
                write!(f, "section has {rows} rows, above the cap of {max}")
            }
            Self::SectionTooLarge { len, max } => {
                write!(f, "section is {len} bytes, above the cap of {max}")
            }
            Self::TooManyRowGroups { groups, max } => {
                write!(f, "section has {groups} row groups, above the cap of {max}")
            }
            Self::MissingColumn { name } => write!(f, "decoded section lacks column {name:?}"),
            Self::ColumnType { name } => write!(f, "decoded column {name:?} has the wrong type"),
            Self::NullInRequiredColumn { name } => {
                write!(
                    f,
                    "decoded column {name:?} has a NULL but the contract forbids it"
                )
            }
            Self::UnknownType { type_id } => write!(f, "no registered type has id {type_id}"),
            Self::SchemaMismatch => {
                write!(f, "decoded section schema does not match the contract")
            }
        }
    }
}

impl Error for CodecError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Arrow(err) => Some(err),
            Self::Parquet(err) => Some(err),
            Self::TooManyRows { .. }
            | Self::SectionTooLarge { .. }
            | Self::TooManyRowGroups { .. }
            | Self::MissingColumn { .. }
            | Self::ColumnType { .. }
            | Self::NullInRequiredColumn { .. }
            | Self::UnknownType { .. }
            | Self::SchemaMismatch => None,
        }
    }
}

impl From<arrow_schema::ArrowError> for CodecError {
    fn from(err: arrow_schema::ArrowError) -> Self {
        Self::Arrow(err)
    }
}

impl From<parquet::errors::ParquetError> for CodecError {
    fn from(err: parquet::errors::ParquetError) -> Self {
        Self::Parquet(err)
    }
}

/// Build the Arrow schema of a section from its contract.
///
/// The returned schema uses the contract's column order, Arrow types, and
/// nullability.
#[must_use]
pub fn arrow_schema(contract: &TypeContract) -> SchemaRef {
    let fields: Vec<Field> = contract
        .columns
        .iter()
        .map(|column| {
            let data_type = match column.ty {
                ColumnType::I8 => DataType::Int8,
                ColumnType::I16 => DataType::Int16,
                ColumnType::I32 => DataType::Int32,
                ColumnType::I64 | ColumnType::Ts => DataType::Int64,
                ColumnType::U8 => DataType::UInt8,
                ColumnType::U16 => DataType::UInt16,
                ColumnType::U32 => DataType::UInt32,
                ColumnType::U64 => DataType::UInt64,
                ColumnType::F32 => DataType::Float32,
                ColumnType::F64 => DataType::Float64,
                ColumnType::Bool => DataType::Boolean,
            };
            Field::new(column.name, data_type, column.nullable)
        })
        .collect();
    Arc::new(Schema::new(fields))
}

// ---- Encode runtime --------------------------------------------------------

/// Build a required primitive column from one value per row.
#[must_use]
pub fn write_required<T: ArrowPrimitiveType>(values: impl Iterator<Item = T::Native>) -> ArrayRef {
    Arc::new(PrimitiveArray::<T>::from_iter_values(values))
}

/// Build a nullable primitive column; `None` becomes a `NULL` cell.
#[must_use]
pub fn write_nullable<T: ArrowPrimitiveType>(
    values: impl Iterator<Item = Option<T::Native>>,
) -> ArrayRef {
    Arc::new(values.collect::<PrimitiveArray<T>>())
}

/// Build a required boolean column.
#[must_use]
pub fn write_bool(values: impl Iterator<Item = bool>) -> ArrayRef {
    Arc::new(values.map(Some).collect::<BooleanArray>())
}

/// Build a nullable boolean column.
#[must_use]
pub fn write_bool_nullable(values: impl Iterator<Item = Option<bool>>) -> ArrayRef {
    Arc::new(values.collect::<BooleanArray>())
}

/// Encode pre-built columns into a Parquet section body (zstd).
///
/// Owns the framing every snapshot codec shares: the row cap, the zstd
/// level, and the writer options that strip the redundant `ARROW:schema`
/// blob and clear the Arrow-version string so output stays small and
/// deterministic (README.md, "Snapshot Sections"). The columns must be in
/// contract order; [`arrow_schema`] checks that against `contract`.
///
/// # Errors
///
/// [`CodecError::TooManyRows`] above the cap; [`CodecError::Arrow`] or
/// [`CodecError::Parquet`] if Arrow rejects the batch or writing fails.
pub fn encode_section(
    contract: &TypeContract,
    row_count: usize,
    columns: Vec<ArrayRef>,
) -> Result<Vec<u8>, CodecError> {
    if row_count > MAX_SECTION_ROWS {
        return Err(CodecError::TooManyRows {
            rows: row_count,
            max: MAX_SECTION_ROWS,
        });
    }

    let schema = arrow_schema(contract);
    let batch = RecordBatch::try_new(Arc::clone(&schema), columns)?;

    let props = WriterProperties::builder()
        .set_compression(Compression::ZSTD(ZstdLevel::try_new(3)?))
        .set_max_row_group_size(MAX_SECTION_ROWS)
        .set_created_by(String::new())
        .build();
    let options = ArrowWriterOptions::new()
        .with_properties(props)
        .with_skip_arrow_metadata(true);

    let mut buf = Vec::new();
    let mut writer = ArrowWriter::try_new_with_options(&mut buf, schema, options)?;
    writer.write(&batch)?;
    writer.close()?;
    Ok(buf)
}

// ---- Decode runtime --------------------------------------------------------

/// Build a reader with every pre-iteration memory bound applied (README.md,
/// "Memory Bounds"): the byte length is capped before the footer is parsed,
/// the row-group count after it, and the claimed row count at
/// [`MAX_SECTION_ROWS`]. Both decode paths share this so neither can omit a cap.
fn capped_reader(bytes: &[u8]) -> Result<ParquetRecordBatchReader, CodecError> {
    if bytes.len() > MAX_SECTION_BYTES {
        return Err(CodecError::SectionTooLarge {
            len: bytes.len(),
            max: MAX_SECTION_BYTES,
        });
    }
    let data = bytes::Bytes::copy_from_slice(bytes);
    let builder = ParquetRecordBatchReaderBuilder::try_new(data)?;

    let groups = builder.metadata().num_row_groups();
    if groups > MAX_ROW_GROUPS {
        return Err(CodecError::TooManyRowGroups {
            groups,
            max: MAX_ROW_GROUPS,
        });
    }

    let claimed = builder.metadata().file_metadata().num_rows();
    let claimed_rows = usize::try_from(claimed).ok();
    if claimed_rows.is_none_or(|rows| rows > MAX_SECTION_ROWS) {
        return Err(CodecError::TooManyRows {
            rows: claimed_rows.unwrap_or(usize::MAX),
            max: MAX_SECTION_ROWS,
        });
    }

    let batch_size = MAX_SECTION_ROWS.min(8192);
    Ok(builder.with_batch_size(batch_size).build()?)
}

/// Decode a Parquet section body, calling `push_rows` for each read batch.
///
/// Streams: each batch is dropped after `push_rows`, so peak memory is one
/// batch plus the decoded rows, both bounded by [`MAX_SECTION_ROWS`]. The
/// caller's closure only extracts columns and appends rows, so a generated
/// codec cannot omit a cap.
///
/// # Errors
///
/// [`CodecError::SectionTooLarge`], [`CodecError::TooManyRowGroups`], or
/// [`CodecError::TooManyRows`] if a bound is exceeded; [`CodecError::Parquet`]
/// on malformed Parquet; whatever `push_rows` returns on a contract mismatch.
pub fn decode_section<Row>(
    bytes: &[u8],
    mut push_rows: impl FnMut(&RecordBatch, &mut Vec<Row>) -> Result<(), CodecError>,
) -> Result<Vec<Row>, CodecError> {
    let reader = capped_reader(bytes)?;
    let mut rows = Vec::new();
    for batch in reader {
        let batch = batch?;
        if rows.len() + batch.num_rows() > MAX_SECTION_ROWS {
            return Err(CodecError::TooManyRows {
                rows: rows.len() + batch.num_rows(),
                max: MAX_SECTION_ROWS,
            });
        }
        push_rows(&batch, &mut rows)?;
    }
    Ok(rows)
}

/// Decode a section body to its Arrow batches, validated against `contract`.
///
/// The registry-driven counterpart to [`decode_section`]: it takes no concrete
/// Rust type, so [`decode_any`](crate::decode_any) can dispatch by `type_id`.
/// Same caps as [`decode_section`]; the returned batches hold the whole section
/// (bounded by [`MAX_SECTION_ROWS`]). The file schema must match the contract's
/// [`arrow_schema`] in column set, order, type, and nullability.
///
/// # Errors
///
/// [`CodecError::SectionTooLarge`], [`CodecError::TooManyRowGroups`], or
/// [`CodecError::TooManyRows`] on a bound; [`CodecError::SchemaMismatch`] if the
/// file does not match `contract`; [`CodecError::Parquet`] on malformed Parquet.
pub fn decode_batches(
    contract: &TypeContract,
    bytes: &[u8],
) -> Result<Vec<RecordBatch>, CodecError> {
    let reader = capped_reader(bytes)?;

    let want = arrow_schema(contract);
    let got = reader.schema();
    let schema_matches = got.fields().len() == want.fields().len()
        && got.fields().iter().zip(want.fields()).all(|(g, w)| {
            g.name() == w.name()
                && g.data_type() == w.data_type()
                && g.is_nullable() == w.is_nullable()
        });
    if !schema_matches {
        return Err(CodecError::SchemaMismatch);
    }

    let mut batches = Vec::new();
    let mut total = 0_usize;
    for batch in reader {
        let batch = batch?;
        total += batch.num_rows();
        if total > MAX_SECTION_ROWS {
            return Err(CodecError::TooManyRows {
                rows: total,
                max: MAX_SECTION_ROWS,
            });
        }
        batches.push(batch);
    }
    Ok(batches)
}

fn primitive_column<'a, T: ArrowPrimitiveType>(
    batch: &'a RecordBatch,
    name: &'static str,
) -> Result<&'a PrimitiveArray<T>, CodecError> {
    let column = batch
        .column_by_name(name)
        .ok_or(CodecError::MissingColumn { name })?;
    column
        .as_any()
        .downcast_ref::<PrimitiveArray<T>>()
        .ok_or(CodecError::ColumnType { name })
}

/// A required primitive column: rejects a `NULL` so it cannot read as `0`.
///
/// # Errors
///
/// [`CodecError::MissingColumn`], [`CodecError::ColumnType`], or
/// [`CodecError::NullInRequiredColumn`].
pub fn required_column<'a, T: ArrowPrimitiveType>(
    batch: &'a RecordBatch,
    name: &'static str,
) -> Result<&'a PrimitiveArray<T>, CodecError> {
    let array = primitive_column::<T>(batch, name)?;
    if array.null_count() == 0 {
        Ok(array)
    } else {
        Err(CodecError::NullInRequiredColumn { name })
    }
}

/// A nullable primitive column.
///
/// # Errors
///
/// [`CodecError::MissingColumn`] or [`CodecError::ColumnType`].
pub fn nullable_column<'a, T: ArrowPrimitiveType>(
    batch: &'a RecordBatch,
    name: &'static str,
) -> Result<&'a PrimitiveArray<T>, CodecError> {
    primitive_column::<T>(batch, name)
}

fn boolean_column<'a>(
    batch: &'a RecordBatch,
    name: &'static str,
) -> Result<&'a BooleanArray, CodecError> {
    let column = batch
        .column_by_name(name)
        .ok_or(CodecError::MissingColumn { name })?;
    column
        .as_any()
        .downcast_ref::<BooleanArray>()
        .ok_or(CodecError::ColumnType { name })
}

/// A required boolean column.
///
/// # Errors
///
/// [`CodecError::MissingColumn`], [`CodecError::ColumnType`], or
/// [`CodecError::NullInRequiredColumn`].
pub fn required_bool<'a>(
    batch: &'a RecordBatch,
    name: &'static str,
) -> Result<&'a BooleanArray, CodecError> {
    let array = boolean_column(batch, name)?;
    if array.null_count() == 0 {
        Ok(array)
    } else {
        Err(CodecError::NullInRequiredColumn { name })
    }
}

/// A nullable boolean column.
///
/// # Errors
///
/// [`CodecError::MissingColumn`] or [`CodecError::ColumnType`].
pub fn nullable_bool<'a>(
    batch: &'a RecordBatch,
    name: &'static str,
) -> Result<&'a BooleanArray, CodecError> {
    boolean_column(batch, name)
}

/// Read primitive cell `i` as `Option`, mapping a null cell to `None`.
#[must_use]
pub fn opt_primitive<T: ArrowPrimitiveType>(
    array: &PrimitiveArray<T>,
    i: usize,
) -> Option<T::Native> {
    if array.is_null(i) {
        None
    } else {
        Some(array.value(i))
    }
}

/// Read boolean cell `i` as `Option`, mapping a null cell to `None`.
#[must_use]
pub fn opt_bool(array: &BooleanArray, i: usize) -> Option<bool> {
    if array.is_null(i) {
        None
    } else {
        Some(array.value(i))
    }
}

#[cfg(test)]
mod hygiene_tests {
    use crate::Section;

    // Fields named like the identifiers the generated encode/decode use
    // internally (`batch`, `out`, `i`, `rows`, `columns`). This must compile
    // and roundtrip: a hygiene regression in the derive would break the build.
    #[derive(Debug, Clone, Copy, PartialEq, Section)]
    #[section(id = 1_099_001, name = "hygiene probe", semantics = snapshot_full, sort_key("ts"))]
    struct Weird {
        #[column(t)]
        ts: i64,
        #[column(c)]
        batch: i64,
        #[column(c)]
        out: i64,
        #[column(c)]
        i: i64,
        #[column(c)]
        rows: Option<i64>,
        #[column(g)]
        columns: bool,
    }

    #[test]
    fn collision_named_fields_roundtrip() {
        let want = vec![
            Weird {
                ts: 1,
                batch: 2,
                out: 3,
                i: 4,
                rows: Some(5),
                columns: true,
            },
            Weird {
                ts: 6,
                batch: 7,
                out: 8,
                i: 9,
                rows: None,
                columns: false,
            },
        ];
        let bytes = Weird::encode(&want).expect("encode");
        assert_eq!(Weird::decode(&bytes).expect("decode"), want);
    }
}
