//! Section type ids, contracts, and codecs.
//!
//! The registry defines what each `type_id` means: class, schema, column
//! classes, sort key, and collection semantics. Each type is a struct with
//! `#[derive(Section)]` (`kronika-derive`), which generates its contract and
//! Parquet codec. This crate also contains shared codec code and a linter that
//! checks contract invariants.
//!
//! See the crate README for the `type_id` scheme, the contract model, the
//! registry linter, and the snapshot-section format.

// The codec generated by `#[derive(Section)]` refers to this crate by name,
// so it must be nameable from inside the crate too.
extern crate self as kronika_registry;

mod codec;
mod contract;
mod pool;
mod section;
mod type_id;

pub use codec::{
    CodecError, DecodeStats, DecodedSection, MAX_ROW_GROUPS, MAX_SECTION_BYTES, MAX_SECTION_ROWS,
    VerifiedSection, arrow_schema, decode_batches, decode_section, encode_section, nullable_bool,
    nullable_column, opt_bool, opt_primitive, required_bool, required_column, write_bool,
    write_bool_nullable, write_nullable, write_required,
};
pub use codec::{bgwriter_checkpointer, instance_metadata, reset_metadata};
pub use contract::{
    Column, ColumnClass, ColumnType, LintError, Semantics, StrId, Ts, TypeContract, lint,
};
pub use pool::{BytesPool, PoolStats};
pub use section::Section;
#[cfg(test)]
pub(crate) use section::assert_roundtrips;
pub use type_id::{SectionClass, TypeId};

// One `Bytes` for the decode API and derived codecs to name.
pub use bytes::Bytes;

// The `Section` derive macro is internal to the registry. Every section type is
// defined in this crate, and an external `#[derive(Section)]` cannot reach the
// crate-private `TypeId` constructor. The trait above is public; the derive
// macro is not.
pub(crate) use kronika_derive::Section;

// Arrow primitive type tokens that `#[derive(Section)]` names in generated
// codecs, re-exported so a type module needs only this crate in scope.
pub use arrow_array::types::{
    Float32Type, Float64Type, Int8Type, Int16Type, Int32Type, Int64Type, UInt8Type, UInt16Type,
    UInt32Type, UInt64Type,
};

/// Every type id known to this build, in registry order.
///
/// Retired types stay here marked [`TypeContract::deprecated`]; ids are never
/// reused.
#[must_use]
pub const fn registry() -> &'static [TypeContract] {
    &[
        bgwriter_checkpointer::BgwriterCheckpointer::CONTRACT,
        reset_metadata::ResetMetadata::CONTRACT,
        instance_metadata::InstanceMetadata::CONTRACT,
    ]
}

/// Decode a section body by selecting its contract from [`registry`].
///
/// The registry-driven reader entry point: it takes no concrete type, so a new
/// section type costs one [`registry`] entry and no per-type `match` here. The
/// returned [`DecodedSection`] carries the contract's columns and the
/// [`DecodeStats`] the caller exports as metrics; the bytes are validated
/// against the contract (README.md, "Section Trait").
///
/// Lookup is a linear scan of [`registry`] — negligible at the current size;
/// a perfect-hash lookup would replace it if the registry grows to hundreds of
/// types.
///
/// Integrity is in the type: it takes a [`VerifiedSection`], whose only
/// constructor verifies the section CRC (the crc function injected from the
/// container layer), so unverified bytes cannot reach the Parquet parser by
/// accident. A segment deliberately rebuilt with a matching CRC is outside the
/// protection model (README.md, "Memory Bounds").
///
/// # Errors
///
/// [`CodecError::UnknownType`] if no registered type has `type_id`; otherwise a
/// [`CodecError::Section`] wrapping the underlying decode error with `type_id`
/// and `bytes_in`, so a failure carries the same label as [`DecodeStats`] does
/// on success. Both error variants carry `type_id`, so a reader can label every
/// outcome — decoded, unknown, or failed — with no unlabeled fallthrough.
pub fn decode_any(type_id: u32, section: VerifiedSection) -> Result<DecodedSection, CodecError> {
    let contract = registry()
        .iter()
        .find(|contract| contract.type_id.get() == type_id)
        .ok_or(CodecError::UnknownType { type_id })?;
    let bytes_in = section.len();
    decode_batches(contract, section).map_err(|source| CodecError::Section {
        type_id,
        bytes_in,
        source: Box::new(source),
    })
}

/// Decode a section read into a pooled buffer.
///
/// `fill` writes the section bytes into a buffer borrowed from `pool` (reused
/// across calls, so a steady decode loop does not allocate per section); the
/// bytes are CRC-verified ([`VerifiedSection::verify`], `crc32c` and
/// `expected_crc` from the catalog) and passed to [`decode_any`].
///
/// # Errors
///
/// [`CodecError::SectionCrcMismatch`] on a CRC mismatch; otherwise the errors of
/// [`decode_any`].
pub fn decode_pooled(
    pool: &BytesPool,
    type_id: u32,
    expected_crc: u32,
    crc32c: impl FnOnce(&[u8]) -> u32,
    fill: impl FnOnce(&mut Vec<u8>),
) -> Result<DecodedSection, CodecError> {
    let section = VerifiedSection::verify(pool.load(fill), expected_crc, crc32c)?;
    decode_any(type_id, section)
}

/// Run the registry linter over every known type.
///
/// # Errors
///
/// Returns the [`LintError`]s found; this is the check wired into CI
/// (README.md, "Registry Linter").
pub fn lint_registry() -> Result<(), Vec<LintError>> {
    lint(registry())
}

#[cfg(test)]
mod tests {
    use arrow_array::ArrayRef;
    use arrow_array::array::new_empty_array;
    use bytes::Bytes;

    use super::{
        BytesPool, CodecError, VerifiedSection, arrow_schema, decode_any, decode_pooled,
        encode_section, lint_registry, registry,
    };

    #[test]
    fn the_registry_is_clean() {
        assert_eq!(lint_registry(), Ok(()));
    }

    #[test]
    fn registry_is_not_empty() {
        assert!(!registry().is_empty());
    }

    /// Wiring check for every registered type, with no per-type code: an empty
    /// section built from the contract schema must encode and decode back
    /// through `decode_any`. A type added but mis-wired fails here.
    #[test]
    fn every_registered_type_decodes_an_empty_section() {
        for contract in registry() {
            let schema = arrow_schema(contract);
            let columns: Vec<ArrayRef> = schema
                .fields()
                .iter()
                .map(|field| new_empty_array(field.data_type()))
                .collect();
            let bytes = encode_section(contract, 0, columns).expect("encode empty section");
            let bytes_in = bytes.len();
            let id = contract.type_id.get();
            let decoded =
                decode_any(id, VerifiedSection::for_test(bytes.into())).expect("decode_any");
            assert_eq!(decoded.stats.type_id, id, "stats carries the type_id");
            assert_eq!(
                decoded.stats.rows, 0,
                "type {id} decoded a non-empty section"
            );
            assert_eq!(
                decoded.stats.bytes_in, bytes_in,
                "stats.bytes_in matches input"
            );
        }
    }

    #[test]
    fn decode_pooled_reads_into_a_pooled_buffer_and_decodes() {
        let pool = BytesPool::new(2, 1 << 20);
        let contract = &registry()[0];
        let id = contract.type_id.get();
        let columns: Vec<ArrayRef> = arrow_schema(contract)
            .fields()
            .iter()
            .map(|field| new_empty_array(field.data_type()))
            .collect();
        let encoded = encode_section(contract, 0, columns).expect("encode empty section");
        // Stand-in CRC = byte length; production code passes kronika-format's.
        let crc = |b: &[u8]| u32::try_from(b.len()).unwrap_or(u32::MAX);
        let expected = crc(&encoded);
        let decoded = decode_pooled(&pool, id, expected, crc, |buf| {
            buf.extend_from_slice(&encoded);
        })
        .expect("decode_pooled");
        assert_eq!(decoded.stats.type_id, id);
    }

    #[test]
    fn decode_any_rejects_an_unregistered_type() {
        // Structurally valid (class 2, source 999, version 999) but not in the
        // registry, so decode_any must reject it rather than decode garbage.
        assert!(matches!(
            decode_any(2_999_999, VerifiedSection::for_test(Bytes::new())),
            Err(CodecError::UnknownType { type_id: 2_999_999 })
        ));
    }
}
